config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  get 'columns/index'
  resources :users, only: [:create, :show, :index]
  resources :chats, only: [:index, :create]
  resources :messages, only: [:index, :create]

  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logged_in', to: 'sessions#is_logged_in?'

  get '/columns', to: 'columns#index'
  resources :columns, except: [:create, :destroy]

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    has_many :messages
end

app/models/column.rb
class Column < ApplicationRecord
    has_many :tasks, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :column
  belongs_to :user

  validates :title, :column_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true
    validates :email, uniqueness: true

    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

    enum role: [:patient, :therapist, :admin]

    has_many :messages, dependent: :destroy
    has_many :tasks

    after_initialize do
        if self.new_record?
            self.role ||= :patient
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    skip_before_action :verify_authenticity_token

    helper_method :login!, :logged_in?, :current_user, :authorized_user?, :logout!

    def login!
        session[:user_id] = @user_id
    end

    def logged_in?
        !!session[:user_id]
    end
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorized_user?
        @user == current_user
    end

    def logout!
        session.clear
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
    def index
        chats = Chat.all
        render json: chats
    end

    def create
        chat = Chat.new(chat_params)
        if chat.save
            serialized_data = ActiveModelSerializers::Adapter::Json.new(
                ChatSerializer.new(chat)
            ).serializable_hash
            ActionCable.server.broadcast 'chats_channel', serialized_data
            head :ok
        end
    end

    private

    def chat_params
        params.require(:chat).permit(:name)
    end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :set_column, only: [:show, :edit, :update]

  def index
    columns = Column.order(:id)
    render json: columns, include: {tasks: { include: [:user, :column], except: [:user_id, :column_id]}}
  end

  def show
    render json: @column, include: {tasks: { include: [:user, :column], except: [:user_id, :column_id]}}
  end

  def edit
  end

  def update
    if @column.update(column_params)
      render json: @column, status: :ok, location: @column, include: {tasks: { include: [:user, :column], except: [:user_id, :column_id]}}
    else
      render json: @column.errors, status: :unprocessable_entity
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_column
    @column = Column.find_by(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def column_params
    params.require(:column).permit(:label, :value, :id, :created_at, :updated_at)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def index
        messages = Message.all
        render json: messages
    end


    def create
        message = Message.new(message_params)
        chat = Chat.find(message_params[:chat_id])
        if message.save
            serialized_data = ActiveModelSerializers::Adapter::Json.new(
                MessageSerializer.new(message)
            ).serializable_hash
            MessagesChannel.broadcast_to chat, serialized_data
            head :ok
        end
    end

    private

    def message_params
        params.require(:message).permit(:chat_id, :user_id, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        @user = User.find_by(email: session_params[:email])

        if @user && @user.authenticate(session_params[:password])
            login!
            render json: {
                logged_in: true,
                user: @user
            }
        else
            render json: {
                status: 401,
                errors: ['no such user', 'verify credentials and try again or signup']
            }
        end
    end

    def is_logged_in?
        if logged_in? && current_user
            render json: {
                logged_in: true,
                user: current_user
            }
        else
            render json: {
                logged_in: false,
                message: 'no such user'
            }
        end
    end

    def destroy
        logout!
        render json: {
            status: 200,
            logged_out: true
        }
    end

    private

    def session_params
        params.require(:user).permit(:email, :password)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks or /tasks.json 
  def index
    tasks = Task.all
    render json: tasks, include: [:user, :column], except: [:user_id, :column_id]
  end

  def show
    render json: @task, include: [:user, :column], except: [:user_id, :column_id]
  end

  # GET /tasks/new
  def new
    task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    task = Task.new(task_params)

    if task.save
      render json: task, include: [:user, :column], except: [:user_id, :column_id], status: :created, location: task
    else
      render json: task.errors, status: :unprocessable_entity
    end
    
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    if @task.update(task_params)
      render json: @task, status: :ok, location: @task, include: [:user, :column], except: [:user_id, :column_id]
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    head :no_content, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :date, :tag, :column_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
        if @users
            render json: {
                users: @users
            }
        else
            render json: {
                status: 500,
                errors: ['no users found']
            }
        end
    end

    def show
        @user = User.find_by(id: params[:id])
        if @user
            render json: {
                user: @user
            }
        else
            render json: {
                status: 500,
                errors: ['user not found']
            }
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!
            render json: {
                status: :created,
                user: @user
            }
        else
            render json: {
                status: 500,
                errors: @user.errors.full_messages
            }
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :role, :therapist_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/columns/index.html.erb
<h1>Columns#index</h1>
<p>Find me in app/views/columns/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PomRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="field">
    <%= form.label :column_id %>
    <%= form.text_field :column_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Tag</th>
      <th>Column</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.date %></td>
        <td><%= task.tag %></td>
        <td><%= task.column_id %></td>
        <td><%= task.user_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @task.date %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @task.tag %>
</p>

<p>
  <strong>Column:</strong>
  <%= @task.column_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>